const HD_DAILY_OPS_KEY='harbordesk-daily-ops-v1';
const HD_NOTIFY_KEY='harbordesk-notification-settings-v1';
const HD_NOTIFY_FIRED_KEY='harbordesk-notification-fired-v1';
const HD_DAILY_ITEMS=[['quests','受注任務を確認'],['exercise','演習枠を確認'],['expedition','第2〜第4艦隊を遠征へ'],['improve','今日の改修を実施'],['resources','資源を記録/目標確認'],['eo','EO・戦果の進捗確認']];
function hdDOLoad(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}
function hdDOSave(k,v){localStorage.setItem(k,JSON.stringify(v))}
function hdDOEsc(s){return typeof hdEsc==='function'?hdEsc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hdDODayKey(){const d=new Date(Date.now()-5*3600000);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function hdDOState(){const all=hdDOLoad(HD_DAILY_OPS_KEY,{}),key=hdDODayKey();if(!all[key]){all[key]={};for(const [id] of HD_DAILY_ITEMS)all[key][id]=false;const keep={};for(const k of Object.keys(all).sort().slice(-14))keep[k]=all[k];hdDOSave(HD_DAILY_OPS_KEY,keep);return keep[key]||all[key]}return all[key]}
function hdDOSaveState(s){const all=hdDOLoad(HD_DAILY_OPS_KEY,{});all[hdDODayKey()]=s;hdDOSave(HD_DAILY_OPS_KEY,all)}
function hdDOSystemSummary(){let questOpen=0;try{questOpen=(state?.quests||[]).filter(x=>!x.done).length}catch{}let exercise='未確認';try{if(typeof hdERCounts==='function'){const c=hdERCounts();exercise=`${c.battles}/10戦・残り${c.remaining}`}}catch{}let active=0;try{active=(state?.expeditions||[]).filter(x=>x.endsAt>Date.now()).length}catch{}let resourceAlerts=0;try{if(typeof hdRBRows==='function')resourceAlerts=hdRBRows().filter(x=>x.goal>0&&x.current<x.goal).length}catch{}let eoRemain='-';try{if(typeof hdEOLoad==='function'&&typeof hdEOSummary==='function'){const s=hdEOSummary(hdEOLoad());eoRemain=`${Math.max(0,7-s.completed)}海域`}}catch{}return {questOpen,exercise,active,resourceAlerts,eoRemain}}
function hdDORender(){const host=document.getElementById('hdDailyOps');if(!host)return;const s=hdDOState(),sum=hdDOSystemSummary(),done=HD_DAILY_ITEMS.filter(([id])=>s[id]).length;host.innerHTML=`<div class="section-head"><div><div class="eyebrow">DAILY COMMAND</div><h2>デイリー司令部</h2></div><span class="muted">05:00更新｜${done}/${HD_DAILY_ITEMS.length}</span></div><div class="hd-do-summary"><div><span>未完了チェックリスト任務</span><strong>${sum.questOpen}</strong></div><div><span>演習</span><strong>${hdDOEsc(sum.exercise)}</strong></div><div><span>遠征中</span><strong>${sum.active}/3</strong></div><div><span>資源目標未達</span><strong>${sum.resourceAlerts}</strong></div><div><span>EO残り</span><strong>${hdDOEsc(sum.eoRemain)}</strong></div></div><div class="hd-do-checklist">${HD_DAILY_ITEMS.map(([id,label])=>`<label class="${s[id]?'done':''}"><input type="checkbox" data-do-check="${id}" ${s[id]?'checked':''}><span>${hdDOEsc(label)}</span></label>`).join('')}</div><div class="hd-go-note">このチェックはHarborDesk内の「今日やること」用。ゲーム側の達成状態を自動取得するものではないよ。</div>`}
function hdDOEnsure(){if(document.getElementById('dailyOpsCenter'))return;const anchor=document.getElementById('dashboard')||document.getElementById('activityLogger')||document.querySelector('main section');if(!anchor)return;const sec=document.createElement('section');sec.id='dailyOpsCenter';sec.className='advanced-section';sec.innerHTML='<div id="hdDailyOps"></div>';anchor.insertAdjacentElement('afterend',sec);hdDORender()}
function hdDONotifyCfg(){return hdDOLoad(HD_NOTIFY_KEY,{expedition:true,dock:true,construction:true,exercise:true,questReset:true,monthStart:true})}
function hdDONotifyFired(){return hdDOLoad(HD_NOTIFY_FIRED_KEY,{})}
async function hdDONotify(title,body,key){const fired=hdDONotifyFired();if(fired[key])return false;let sent=false;try{if('serviceWorker' in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,tag:key});sent=true}else if('Notification' in window&&Notification.permission==='granted'){new Notification(title,{body,tag:key});sent=true}}catch{}if(sent){fired[key]=Date.now();hdDOSave(HD_NOTIFY_FIRED_KEY,fired)}return sent}
function hdDOCleanupFired(){const f=hdDONotifyFired(),cut=Date.now()-7*86400000;for(const k of Object.keys(f))if(Number(f[k])<cut)delete f[k];hdDOSave(HD_NOTIFY_FIRED_KEY,f)}
function hdDONotificationTick(){if(!('Notification' in window)||Notification.permission!=='granted')return;const cfg=hdDONotifyCfg(),now=Date.now(),near=x=>Number(x?.endsAt)&&Number(x.endsAt)<=now&&Number(x.endsAt)>now-120000;try{if(cfg.expedition)for(const x of (state?.expeditions||[]).filter(near))hdDONotify('遠征が帰投したよ',x.name||'遠征帰投',`exp:${x.id}:${x.endsAt}`);if(cfg.dock)for(const x of (state?.docks||[]).filter(near))hdDONotify('入渠が完了したよ',x.name||'入渠完了',`dock:${x.id}:${x.endsAt}`)}catch{}if(cfg.construction){for(const x of hdDOLoad('harbordesk-construction-timers-v1',[]).filter(near))hdDONotify('建造が完了したよ',x.name||'建造完了',`build:${x.id||x.createdAt}:${x.endsAt}`)}const d=new Date(),hh=d.getHours(),mm=d.getMinutes(),day=hdDODayKey();if(cfg.exercise&&hh===15&&mm<3)hdDONotify('演習相手が更新されたよ','15:00の演習5戦を確認しよう',`exercise15:${day}`);if(cfg.questReset&&hh===5&&mm<3)hdDONotify('任務が更新されたよ','デイリー任務の05:00更新',`quest5:${day}`);if(cfg.monthStart&&d.getDate()===1&&hh===5&&mm<3)hdDONotify('月初更新','EO・マンスリー任務・資源目標を確認しよう',`month:${d.getFullYear()}-${d.getMonth()+1}`)}
function hdDONotifyRender(){const host=document.getElementById('hdNotifyCenter');if(!host)return;const cfg=hdDONotifyCfg(),perm='Notification' in window?Notification.permission:'unsupported',labels=[['expedition','遠征帰投'],['dock','入渠完了'],['construction','建造完了'],['exercise','演習15:00更新'],['questReset','任務05:00更新'],['monthStart','月初更新']];host.innerHTML=`<div class="section-head"><div><div class="eyebrow">NOTIFICATION CENTER</div><h2>通知センター</h2></div><span class="muted">${perm==='granted'?'通知ON':perm==='denied'?'通知拒否':'許可未設定'}</span></div><div class="hd-go-note">iPhoneのPWAでは、Web Push用バックエンドなしで「完全に閉じた状態の時刻指定通知」は保証できない。この通知はHarborDeskが起動中/動作中に条件を検出した時に出す安全な範囲の実装。</div><div class="hd-do-notify-grid">${labels.map(([id,label])=>`<label><input type="checkbox" data-notify-setting="${id}" ${cfg[id]?'checked':''}>${hdDOEsc(label)}</label>`).join('')}</div><div class="hd-go-actions"><button class="primary" type="button" data-notify-permission>${perm==='granted'?'通知許可済み':'通知を許可'}</button><button class="ghost" type="button" data-notify-test>テスト通知</button></div>`}
function hdDONotifyEnsure(){if(document.getElementById('notificationCenter'))return;const anchor=document.getElementById('backup')||document.getElementById('dailyOpsCenter');if(!anchor)return;const sec=document.createElement('section');sec.id='notificationCenter';sec.className='advanced-section';sec.innerHTML='<div id="hdNotifyCenter"></div>';anchor.insertAdjacentElement('beforebegin',sec);hdDONotifyRender();hdDOCleanupFired()}
function hdDOAuditIssues(){const issues=[];const roster=hdDOLoad('harbordesk-ship-roster-v1',[]),profiles=hdDOLoad('harbordesk-ship-profiles-v1',{}),training=hdDOLoad('harbordesk-training-plans-v1',{}),hunts=hdDOLoad('harbordesk-drop-hunts-v1',[]),variants=hdDOLoad('harbordesk-equipment-variants-v1',{}),ledger=hdDOLoad('harbordesk-equipment-v1',[]),plans=hdDOLoad('harbordesk-event-operations-v1',[]);const ids=new Set(roster.map(x=>x.id)),names=new Set(roster.map(x=>x.name)),eq=new Set(ledger.map(x=>x.name));for(const id of Object.keys(training))if(!ids.has(id))issues.push({level:'warn',text:`育成計画に台帳から削除済みの艦ID ${id} が残っている`});for(const id of Object.keys(profiles))if(!ids.has(id))issues.push({level:'warn',text:'詳細プロフィールに削除済み艦のデータが残っている'});for(const h of hunts)if(h.obtained&&!Array.from(names).some(n=>n===h.ship||n.startsWith(h.ship)))issues.push({level:'info',text:`${h.ship} は掘りで入手済みだが艦娘台帳には未登録`});for(const n of Object.keys(variants))if(!eq.has(n))issues.push({level:'warn',text:`★別在庫「${n}」が装備台帳に存在しない`});for(const p of plans){for(const n of [...(p.first||[]),...(p.second||[])].filter(Boolean))if(!names.has(n))issues.push({level:'warn',text:`${p.area} ${p.name}: ${n} が艦娘台帳にない`})}if(typeof HD_MAP_ADVANCED_DATA==='undefined')issues.push({level:'info',text:'海域高度データが未読込。海域画面を開いた後に再監査してね'});if(typeof hdFCRender==='function')issues.push({level:'info',text:'制空/索敵計算は手動艦ステータス・装備入力を含む。イベント前はゲーム表示値で再確認推奨'});issues.push({level:'info',text:'通知はWeb Pushバックエンドなしのため、PWA完全終了中の時刻通知は保証しない'});return issues}
function hdDOAuditCounts(){const keys=['harbordesk-ship-roster-v1','harbordesk-equipment-v1','harbordesk-sortie-log-v1','harbordesk-drop-hunts-v1','harbordesk-event-operations-v1','harbordesk-activity-log-v1'];return keys.map(k=>{const v=hdDOLoad(k,[]);return [k,Array.isArray(v)?v.length:Object.keys(v||{}).length]})}
function hdDOAuditRender(){const host=document.getElementById('hdDataAudit');if(!host)return;const issues=hdDOAuditIssues(),counts=hdDOAuditCounts();host.innerHTML=`<div class="section-head"><div><div class="eyebrow">DATA QUALITY</div><h2>データ品質・整合性監査</h2></div><button class="ghost small" type="button" data-audit-refresh>再監査</button></div><div class="hd-do-audit-counts">${counts.map(([k,n])=>`<div><span>${hdDOEsc(k.replace('harbordesk-','').replace('-v1',''))}</span><strong>${n}</strong></div>`).join('')}</div><div class="hd-do-audit-list">${issues.map(x=>`<div class="${x.level}"><b>${x.level==='warn'?'要確認':'情報'}</b><span>${hdDOEsc(x.text)}</span></div>`).join('')||'<div class="ok"><b>OK</b><span>参照切れは見つからなかったよ。</span></div>'}</div><div class="hd-go-note">静的攻略データそのものの正誤は、機能追加時にWiki等の現行情報で順次監査する。この画面は端末内データの参照切れ・不整合を中心に検査する。</div>`}
function hdDOAuditEnsure(){if(document.getElementById('dataQualityAudit'))return;const anchor=document.getElementById('backup')||document.getElementById('notificationCenter');if(!anchor)return;const sec=document.createElement('section');sec.id='dataQualityAudit';sec.className='advanced-section';sec.innerHTML='<div id="hdDataAudit"></div>';anchor.insertAdjacentElement('beforebegin',sec);hdDOAuditRender()}
(function hdDOPatchCommandCenter(){const install=()=>{if(typeof window.hdCCPriorityItems!=='function'||window.__hdDOPatch)return;const orig=window.hdCCPriorityItems;window.hdCCPriorityItems=function(){let items=orig();const s=hdDOState(),left=HD_DAILY_ITEMS.filter(([id])=>!s[id]).length;if(left)items.push({score:70,icon:'✅',title:`今日の司令部 残り${left}項目`,detail:'デイリーチェックリストを確認',target:'dailyOpsCenter'});items.sort((a,b)=>b.score-a.score);return items.slice(0,8)};window.__hdDOPatch=true};setTimeout(install,2500);window.addEventListener('load',()=>setTimeout(install,1800))})()
document.addEventListener('change',e=>{const c=e.target.closest?.('[data-do-check]');if(c){const s=hdDOState();s[c.dataset.doCheck]=c.checked;hdDOSaveState(s);hdDORender();try{if(typeof hdCCRender==='function')hdCCRender()}catch{}return}const n=e.target.closest?.('[data-notify-setting]');if(n){const cfg=hdDONotifyCfg();cfg[n.dataset.notifySetting]=n.checked;hdDOSave(HD_NOTIFY_KEY,cfg);hdDONotifyRender()}})
document.addEventListener('click',async e=>{if(e.target.closest?.('[data-notify-permission]')){if('Notification' in window)await Notification.requestPermission();hdDONotifyRender();return}if(e.target.closest?.('[data-notify-test]')){if('Notification' in window&&Notification.permission==='granted')await hdDONotify('HarborDesk テスト通知','通知センターは動作中だよ',`test:${Date.now()}`);else alert('先に通知を許可してね');return}if(e.target.closest?.('[data-audit-refresh]')){hdDOAuditRender();return}})
window.addEventListener('load',()=>setTimeout(()=>{hdDOEnsure();hdDONotifyEnsure();hdDOAuditEnsure();hdDONotificationTick()},2200));setTimeout(()=>{hdDOEnsure();hdDONotifyEnsure();hdDOAuditEnsure()},3000);setInterval(()=>{hdDORender();hdDONotificationTick()},60000);