const HD_EXERCISE_ROUTINE_KEY='harbordesk-exercise-routine-v1';

function hdERLoad(){try{return JSON.parse(localStorage.getItem(HD_EXERCISE_ROUTINE_KEY)||'{}')||{}}catch{return {}}}
function hdERSave(v){localStorage.setItem(HD_EXERCISE_ROUTINE_KEY,JSON.stringify(v))}
function hdERPad(n){return String(n).padStart(2,'0')}
function hdERDayKey(d=new Date()){const x=new Date(d.getTime()-3*60*60*1000);return `${x.getFullYear()}-${hdERPad(x.getMonth()+1)}-${hdERPad(x.getDate())}`}
function hdERBatch(d=new Date()){const h=d.getHours();return h>=3&&h<15?'morning':'afternoon'}
function hdEREmptySlot(){return {result:'',trainingId:'',questKeys:{},recordedAt:0}}
function hdERDefaultDay(key=hdERDayKey()){return {key,morning:Array.from({length:5},hdEREmptySlot),afternoon:Array.from({length:5},hdEREmptySlot),selectedTrainingId:''}}
function hdERCurrent(){const all=hdERLoad(),key=hdERDayKey();if(!all[key]){all[key]=hdERDefaultDay(key);const keys=Object.keys(all).sort().slice(-14),keep={};for(const k of keys)keep[k]=all[k];hdERSave(keep);return keep[key]||all[key]}return all[key]}
function hdERSaveCurrent(day){const all=hdERLoad();all[day.key]=day;const keys=Object.keys(all).sort().slice(-14),keep={};for(const k of keys)keep[k]=all[k];hdERSave(keep)}
function hdEREsc(s){return typeof hdEsc==='function'?hdEsc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hdERNextRefresh(){const n=new Date(),t=new Date(n);if(n.getHours()<3)t.setHours(3,0,0,0);else if(n.getHours()<15)t.setHours(15,0,0,0);else{t.setDate(t.getDate()+1);t.setHours(3,0,0,0)}const ms=t-n,h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);return {at:t,text:`${hdERPad(t.getHours())}:00まで あと${h}時間${m}分`}}
function hdERQuestById(id){try{return typeof HD_QUESTS!=='undefined'?HD_QUESTS.find(q=>q.id===id):null}catch{return null}}
function hdERPeriodKey(q){try{return typeof hdQPPeriodKey==='function'?hdQPPeriodKey(q):''}catch{return ''}}
function hdERQuestKeyAt(q,ts){const d=new Date((Number(ts)||Date.now())-5*60*60*1000),y=d.getFullYear(),m=d.getMonth()+1,day=d.getDate();if(q?.id==='Cm1'||q?.cycle==='daily')return `D:${y}-${hdERPad(m)}-${hdERPad(day)}`;if(q?.cycle==='weekly'){const w=new Date(d);const wd=(w.getDay()+6)%7;w.setDate(w.getDate()-wd);return `W:${w.getFullYear()}-${hdERPad(w.getMonth()+1)}-${hdERPad(w.getDate())}`}return hdERPeriodKey(q)}
function hdERQuestDelta(id,delta,periodKey){if(!delta)return;const q=hdERQuestById(id);if(!q||typeof hdQPGoals!=='function')return;const goals=hdQPGoals(q);if(!goals.length)return;const currentKey=hdERPeriodKey(q),key=periodKey||currentKey;if(key!==currentKey)return;let all={};try{all=typeof hdQPStore==='function'?hdQPStore():JSON.parse(localStorage.getItem('harbordesk-quest-progress-v1')||'{}')||{}}catch{}let row=all[id];if(!row||row.periodKey!==key){if(delta<0)return;row={periodKey:key,values:Array(goals.length).fill(0)}}const max=Number(goals[0]?.[1])||9999;row.values=row.values||[];row.values[0]=Math.max(0,Math.min(max,(Number(row.values[0])||0)+delta));row.updatedAt=Date.now();all[id]=row;try{if(typeof hdQPSave==='function')hdQPSave(all);else localStorage.setItem('harbordesk-quest-progress-v1',JSON.stringify(all))}catch{}}
function hdERTrainingRows(){const roster=(()=>{try{return JSON.parse(localStorage.getItem('harbordesk-ship-roster-v1')||'[]')||[]}catch{return []}})(),plans=(()=>{try{return JSON.parse(localStorage.getItem('harbordesk-training-plans-v1')||'{}')||{}}catch{return {}}})();return roster.filter(s=>plans[s.id]?.active).map(s=>({ship:s,plan:plans[s.id]})).sort((a,b)=>(Number(b.plan.priority)||2)-(Number(a.plan.priority)||2)||String(a.ship.name).localeCompare(String(b.ship.name),'ja'))}
function hdERTrainingDelta(id,delta){if(!id||!delta)return;let plans={};try{plans=JSON.parse(localStorage.getItem('harbordesk-training-plans-v1')||'{}')||{}}catch{}if(!plans[id])return;plans[id].exercises=Math.max(0,(Number(plans[id].exercises)||0)+delta);localStorage.setItem('harbordesk-training-plans-v1',JSON.stringify(plans));try{if(typeof hdRenderTrainingPlanner==='function')hdRenderTrainingPlanner()}catch{}}

function hdERSetResult(batch,index,result){const day=hdERCurrent(),slot=day[batch]?.[index];if(!slot)return;const prev=slot.result||'';if(prev===result)return;
 if(!prev&&result){slot.recordedAt=Date.now();const qkeys={};for(const id of ['Cd1']){const q=hdERQuestById(id),key=q?hdERQuestKeyAt(q,slot.recordedAt):'';qkeys[id]=key;hdERQuestDelta(id,1,key)}if(result==='win')for(const id of ['Cd2','Cw1','Cm1']){const q=hdERQuestById(id),key=q?hdERQuestKeyAt(q,slot.recordedAt):'';qkeys[id]=key;hdERQuestDelta(id,1,key)}slot.questKeys=qkeys;if(day.selectedTrainingId){slot.trainingId=day.selectedTrainingId;hdERTrainingDelta(slot.trainingId,1)}}
 else if(prev&&!result){hdERQuestDelta('Cd1',-1,slot.questKeys?.Cd1);if(prev==='win')for(const id of ['Cd2','Cw1','Cm1'])hdERQuestDelta(id,-1,slot.questKeys?.[id]);if(slot.trainingId)hdERTrainingDelta(slot.trainingId,-1);slot.trainingId='';slot.questKeys={};slot.recordedAt=0}
 else if(prev==='win'&&result!=='win'){for(const id of ['Cd2','Cw1','Cm1'])hdERQuestDelta(id,-1,slot.questKeys?.[id]);for(const id of ['Cd2','Cw1','Cm1'])if(slot.questKeys)delete slot.questKeys[id]}
 else if(prev!=='win'&&result==='win'){slot.questKeys=slot.questKeys||{};const ts=slot.recordedAt||Date.now();for(const id of ['Cd2','Cw1','Cm1']){const q=hdERQuestById(id),key=q?hdERQuestKeyAt(q,ts):'';slot.questKeys[id]=key;hdERQuestDelta(id,1,key)}}
 slot.result=result;hdERSaveCurrent(day);try{if(typeof hdRenderQuestDb==='function')hdRenderQuestDb();if(typeof hdCCRender==='function')hdCCRender()}catch{}hdERRender()}
function hdERSetTraining(id){const day=hdERCurrent();day.selectedTrainingId=id||'';hdERSaveCurrent(day);hdERRender()}
function hdERCounts(day=hdERCurrent()){const slots=[...(day.morning||[]),...(day.afternoon||[])],battles=slots.filter(x=>x.result).length,wins=slots.filter(x=>x.result==='win').length;return {battles,wins,remaining:Math.max(0,10-battles),morning:(day.morning||[]).filter(x=>x.result).length,afternoon:(day.afternoon||[]).filter(x=>x.result).length}}
function hdERBatchHtml(day,batch,label){const rows=day[batch]||[],active=hdERBatch()===batch;return `<article class="hd-er-batch${active?' active':''}"><div class="hd-er-batch-head"><div><strong>${label}</strong><span>${active?'現在の演習枠':''}</span></div><b>${rows.filter(x=>x.result).length}/5</b></div><div class="hd-er-slots">${rows.map((s,i)=>`<div class="hd-er-slot ${s.result||'empty'}"><span>${i+1}</span><div><button type="button" class="${s.result==='win'?'primary':'ghost'} small" data-hd-er-result="win" data-batch="${batch}" data-index="${i}">勝利</button><button type="button" class="${s.result==='loss'?'primary':'ghost'} small" data-hd-er-result="loss" data-batch="${batch}" data-index="${i}">敗北</button><button type="button" class="ghost small" data-hd-er-result="" data-batch="${batch}" data-index="${i}" ${s.result?'':'disabled'}>取消</button></div>${s.trainingId?`<small>育成カウント済み</small>`:''}</div>`).join('')}</div></article>`}
function hdERRender(){const host=document.getElementById('hdExerciseRoutine');if(!host)return;const day=hdERCurrent(),c=hdERCounts(day),next=hdERNextRefresh(),train=hdERTrainingRows(),h=new Date().getHours(),special=h>=3&&h<5;host.innerHTML=`<div class="section-head"><div><div class="eyebrow">DAILY EXERCISE</div><h2>演習・デイリールーチン</h2></div><span class="muted">${hdEREsc(day.key)}</span></div><div class="hd-er-note">演習相手は3:00 / 15:00に各5人更新。デイリー任務は5:00更新なので、3:00〜5:00は任務日付とのズレに注意。</div>${special?'<div class="hd-er-alert">⚠️ 今は3:00〜5:00。ここで記録した演習は、デイリー任務では前日の5:00周期へ加算するよ。</div>':''}<div class="hd-er-summary"><div><span>実施</span><strong>${c.battles}/10</strong></div><div><span>勝利</span><strong>${c.wins}</strong></div><div><span>残り</span><strong>${c.remaining}</strong></div><div><span>次回更新</span><strong>${hdEREsc(next.text)}</strong></div></div><div class="hd-er-training"><label>演習した育成艦にも+1<select id="hdERTrainingSelect"><option value="">連動しない</option>${train.map(x=>`<option value="${hdEREsc(x.ship.id)}" ${day.selectedTrainingId===x.ship.id?'selected':''}>${hdEREsc(x.ship.name)} Lv.${Number(x.ship.level)||1}</option>`).join('')}</select></label><small>選択中の艦は、新しく勝敗を記録した時だけ育成計画の「演習+1」に加算。</small></div><div class="hd-er-grid">${hdERBatchHtml(day,'morning','03:00更新分')}${hdERBatchHtml(day,'afternoon','15:00更新分')}</div><div class="hd-er-sync"><span>勝敗記録は Cd1「演習3回」・Cd2「演習5勝」・Cw1「20勝」・Cm1「同日7勝」の進捗にも反映。</span><button type="button" class="ghost small" data-hd-er-quest>任務DBを見る</button></div>`}
function hdEREnsure(){if(document.getElementById('exerciseRoutine'))return;const anchor=document.getElementById('questDatabase')||document.getElementById('trainingPlanner')||document.getElementById('quests');if(!anchor)return;const sec=document.createElement('section');sec.id='exerciseRoutine';sec.className='advanced-section';sec.innerHTML='<div id="hdExerciseRoutine"></div>';anchor.insertAdjacentElement('beforebegin',sec);hdERRender()}

(function hdERInstallCorrections(){if(typeof window.hdQPPeriodKey==='function'&&!window.__hdCm1PeriodFix){const original=window.hdQPPeriodKey;window.hdQPPeriodKey=function(q){if(q?.id==='Cm1'){const d=typeof hdQPShiftedNow==='function'?hdQPShiftedNow():new Date(Date.now()-5*60*60*1000);return `D:${d.getFullYear()}-${hdERPad(d.getMonth()+1)}-${hdERPad(d.getDate())}`}return original(q)};if(typeof window.hdQPNextReset==='function'){const origNext=window.hdQPNextReset;window.hdQPNextReset=function(q){if(q?.id==='Cm1'){const now=new Date(),n=new Date(now);n.setHours(5,0,0,0);if(now>=n)n.setDate(n.getDate()+1);return `${n.getMonth()+1}/${n.getDate()} ${hdERPad(n.getHours())}:00`}return origNext(q)}}window.__hdCm1PeriodFix=true}})();

(function hdERInstallCommandCenter(){if(typeof window.hdCCPriorityItems==='function'&&!window.__hdERCCPatch){const orig=window.hdCCPriorityItems;window.hdCCPriorityItems=function(){const items=orig();const day=hdERCurrent(),batch=hdERBatch(),done=(day[batch]||[]).filter(x=>x.result).length,remain=Math.max(0,5-done);if(remain>0){items.push({score:74+(remain>=4?4:0),icon:'⚔️',title:`演習 ${batch==='morning'?'03:00':'15:00'}枠 残り${remain}戦`,detail:`今日 ${hdERCounts(day).battles}/10戦・勝利${hdERCounts(day).wins}`,target:'exerciseRoutine'});items.sort((a,b)=>b.score-a.score);return items.slice(0,8)}return items};window.__hdERCCPatch=true}})();

document.addEventListener('click',e=>{const b=e.target.closest?.('[data-hd-er-result]');if(b){hdERSetResult(b.dataset.batch,Number(b.dataset.index),b.dataset.hdErResult);return}if(e.target.closest?.('[data-hd-er-quest]')){if(typeof hdWSShowElement==='function')hdWSShowElement('questDatabase',true);else if(typeof hdQNJump==='function')hdQNJump('questDatabase');else document.getElementById('questDatabase')?.scrollIntoView({behavior:'smooth',block:'start'})}});
document.addEventListener('change',e=>{if(e.target?.id==='hdERTrainingSelect')hdERSetTraining(e.target.value)});
window.addEventListener('load',()=>setTimeout(()=>{hdEREnsure();hdERRender()},1000));setTimeout(hdEREnsure,1400);setInterval(()=>{if(document.getElementById('hdExerciseRoutine'))hdERRender()},60000);
