const HD_OPT_IMPROVE_KEY='harbordesk-improvement-goals-v2';
const HD_RANK_KEY='harbordesk-ranking-tracker-v1';
let hdOptExpResource='fuel';
let hdOptExpMinutes=480;
const HD_OPT_EXP_PRESETS=[30,60,120,240,480,720,1440];
function hdOptExpClamp(minutes){return Math.min(1440,Math.max(15,Math.trunc(Number(minutes)||0)))}
function hdOptExpDuration(minutes){const hours=Math.floor(minutes/60),rest=minutes%60;return `${hours?`${hours}時間`:''}${rest?`${rest}分`:''}`||'0分'}
function hdOptExpSetMinutes(minutes){hdOptExpMinutes=hdOptExpClamp(minutes);hdOptExpRender()}
function hdOptExpUpdateRows(){const host=document.getElementById('hdOptExpRows');if(host)host.innerHTML=hdOptExpRowsHtml();document.querySelectorAll('[data-opt-exp-minutes]').forEach(button=>{const active=Number(button.dataset.optExpMinutes)===hdOptExpMinutes;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});const summary=document.getElementById('hdOptExpDuration');if(summary)summary.textContent=`${hdOptExpDuration(hdOptExpMinutes)}以内の遠征`}
function hdOptExpConditions(exp){const drum=typeof HD_EXP_DRUM_RULES!=='undefined'?HD_EXP_DRUM_RULES[exp.id]:null;return `<div class="hd-opt-exp-conditions"><div><span>成功Lv</span><b>旗艦Lv${exp.flagLv}以上${exp.totalLv!=null?`・艦隊合計Lv${exp.totalLv}以上`:''}</b></div><div><span>必要な編成</span><b>${exp.minShips}隻以上・${hdOptEsc(exp.required)}</b></div>${drum?.successDrums?`<div><span>ドラム缶</span><b>搭載${drum.successShips}隻以上・合計${drum.successDrums}個以上</b></div>`:''}${exp.special?`<p>補足：${hdOptEsc(exp.special)}</p>`:''}</div>`}
function hdOptExpRowsHtml(){const labels={fuel:'燃料',ammo:'弾薬',steel:'鋼材',bauxite:'ボーキ',balanced:'総資源'};return hdOptExpRows().map((x,index)=>{const needsManual=!!x.exp.special&&/ステータス条件|火力|対空|対潜|索敵/.test(x.exp.special);return `<article data-opt-exp-hourly="${x.perHour}"><div><strong>${index+1}位 · ${hdOptEsc(x.exp.id)} ${hdOptEsc(x.exp.name)}</strong><span>${x.exp.minutes}分 / ${labels[hdOptExpResource]} ${Math.round(x.value)}</span></div><div><b>${labels[hdOptExpResource]} ${Math.round(x.perHour)}/時</b><small>${x.fleets.length?`基本条件OK: 第${x.fleets.join('・第')}艦隊${needsManual?'（特殊条件は要確認）':''}`:'登録艦隊では条件不足/使用中'}</small></div>${x.fleets.length?`<button class="primary small" data-opt-exp-set="${x.exp.id}" data-fleet="${x.fleets[0]}">第${x.fleets[0]}艦隊へセット</button>`:''}${hdOptExpConditions(x.exp)}</article>`}).join('')||'<div class="empty">条件に合う遠征がないよ。</div>'}
function hdOptLoad(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}
function hdOptSave(k,v){localStorage.setItem(k,JSON.stringify(v))}
function hdOptEsc(s){return typeof hdEsc==='function'?hdEsc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hdOptUid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2)}
function hdOptImproves(){return typeof HD_IMPROVEMENTS!=='undefined'?HD_IMPROVEMENTS:[]}
function hdOptScrewPair(text){const m=String(text||'').match(/(\d+)\s*\/\s*(\d+)/);return m?[Number(m[1]),Number(m[2])]:[0,0]}
function hdOptGoalEstimate(g){const item=hdOptImproves().find(x=>x.name===g.name);if(!item)return {steps:0,min:0,sure:0};let min=0,sure=0,steps=0;for(let star=Number(g.current)||0;star<Number(g.target)||0;star++){const idx=star<=5?0:1,p=hdOptScrewPair(item.stages?.[idx]?.[2]);min+=p[0];sure+=p[1]||p[0];steps++}if(g.update&&Number(g.target)>=10){const p=hdOptScrewPair(item.stages?.[2]?.[2]);min+=p[0];sure+=p[1]||p[0]}const count=Math.max(1,Number(g.count)||1);return {steps:steps*count,min:min*count,sure:sure*count}}
function hdOptImproveRender(){const host=document.getElementById('hdOptImprove');if(!host)return;const rows=hdOptLoad(HD_OPT_IMPROVE_KEY,[]),items=hdOptImproves();host.innerHTML=`<div class="section-head"><div><div class="eyebrow">IMPROVEMENT GOALS</div><h2>改修目標プランナー</h2></div><button type="button" class="primary small" data-opt-imp-add>＋目標</button></div><div class="hd-go-note">現在の改修工廠データを使った概算。確実化、消費装備、更新素材は実行前に改修工廠カード/Wikiで最終確認してね。</div><div class="hd-opt-goals">${rows.map(g=>{const e=hdOptGoalEstimate(g);return `<article><div><strong>${hdOptEsc(g.name)}</strong><span>★${g.current} → ★${g.target} ×${g.count||1}${g.update?'＋更新':''}</span></div><div class="hd-opt-metrics"><span>残り改修 <b>${e.steps}</b></span><span>ネジ概算 <b>${e.min}〜${e.sure}</b></span></div><div class="hd-opt-actions"><button class="ghost small" data-opt-imp-step="${g.id}">現在★+1</button><button class="ghost small" data-opt-imp-del="${g.id}">削除</button></div></article>`}).join('')||'<div class="empty">改修目標はまだないよ。</div>'}</div><dialog id="hdOptImpDialog"><form method="dialog" id="hdOptImpForm"><h3>改修目標</h3><label>装備<select id="hdOptImpName">${items.map(x=>`<option>${hdOptEsc(x.name)}</option>`).join('')}</select></label><div class="hd-go-grid3"><label>現在★<input id="hdOptImpCur" type="number" min="0" max="10" value="0"></label><label>目標★<input id="hdOptImpTarget" type="number" min="0" max="10" value="10"></label><label>必要数<input id="hdOptImpCount" type="number" min="1" value="1"></label></div><label><input id="hdOptImpUpdate" type="checkbox"> ★MAX後の更新も目標</label><div class="dialog-actions"><button value="cancel" class="ghost">キャンセル</button><button value="default" class="primary">追加</button></div></form></dialog>`;const f=document.getElementById('hdOptImpForm');if(f&&!f.dataset.bound){f.dataset.bound='1';f.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const all=hdOptLoad(HD_OPT_IMPROVE_KEY,[]);all.unshift({id:hdOptUid(),name:document.getElementById('hdOptImpName').value,current:Number(document.getElementById('hdOptImpCur').value)||0,target:Number(document.getElementById('hdOptImpTarget').value)||10,count:Number(document.getElementById('hdOptImpCount').value)||1,update:document.getElementById('hdOptImpUpdate').checked,createdAt:Date.now()});hdOptSave(HD_OPT_IMPROVE_KEY,all);hdOptImproveRender()})}}
function hdOptImproveEnsure(){if(document.getElementById('optimizationImprovement'))return;const anchor=document.getElementById('improvementWorkshop')||document.getElementById('equipmentBook');if(!anchor)return;const sec=document.createElement('section');sec.id='optimizationImprovement';sec.className='advanced-section';sec.innerHTML='<div id="hdOptImprove"></div>';anchor.insertAdjacentElement('afterend',sec);hdOptImproveRender()}
function hdOptExpRows(){const rows=typeof HD_EXPEDITIONS!=='undefined'?HD_EXPEDITIONS:[];return rows.filter(x=>Number(x.minutes)<=hdOptExpMinutes).map(exp=>{const value=hdOptExpResource==='balanced'?['fuel','ammo','steel','bauxite'].reduce((a,k)=>a+(Number(exp.resources?.[k])||0),0):(Number(exp.resources?.[hdOptExpResource])||0),perHour=exp.minutes?value*60/exp.minutes:0;let fleets=[];for(const no of [2,3,4]){try{if(typeof hdEFActiveTimer==='function'&&hdEFActiveTimer(no))continue;const c=typeof hdEFCheck==='function'?hdEFCheck(no,exp):null;if(!c||c.canStart)fleets.push(no)}catch{}}return {exp,value,perHour,fleets}}).filter(x=>x.value>0).sort((a,b)=>b.perHour-a.perHour||a.exp.minutes-b.exp.minutes||a.exp.id.localeCompare(b.exp.id,undefined,{numeric:true})).slice(0,8)}
function hdOptExpRender(){const host=document.getElementById('hdOptExp');if(!host)return;const labels={fuel:'燃料',ammo:'弾薬',steel:'鋼材',bauxite:'ボーキ',balanced:'総資源'};host.innerHTML=`<div class="section-head"><div><div class="eyebrow">EXPEDITION OPTIMIZER</div><h2>遠征おすすめ自動選択</h2></div><span class="muted">選択資源の時給順・上位8件</span></div><div class="hd-go-grid2"><label>優先資源<select id="hdOptExpResource">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${k===hdOptExpResource?'selected':''}>${v}</option>`).join('')}</select></label><div class="hd-opt-exp-time"><span>使える時間</span><div class="hd-opt-exp-time-fields"><label><input id="hdOptExpHours" type="number" inputmode="numeric" min="0" max="24" value="${Math.floor(hdOptExpMinutes/60)}">時間</label><label><input id="hdOptExpMinutes" type="number" inputmode="numeric" min="0" max="59" value="${hdOptExpMinutes%60}">分</label></div></div></div><div class="hd-opt-exp-presets" role="group" aria-label="使える時間を選ぶ">${HD_OPT_EXP_PRESETS.map(minutes=>`<button type="button" class="ghost small${minutes===hdOptExpMinutes?' active':''}" data-opt-exp-minutes="${minutes}" aria-pressed="${minutes===hdOptExpMinutes}">${hdOptExpDuration(minutes)}</button>`).join('')}</div><p id="hdOptExpDuration" class="muted hd-opt-exp-summary">${hdOptExpDuration(hdOptExpMinutes)}以内の遠征</p><div id="hdOptExpRows" class="hd-opt-exp-list">${hdOptExpRowsHtml()}</div>`}
function hdOptExpEnsure(){if(document.getElementById('expeditionOptimizer'))return;const anchor=document.getElementById('expeditionDatabase')||document.getElementById('expeditionFleetManager')||document.getElementById('expeditions');if(!anchor)return;const sec=document.createElement('section');sec.id='expeditionOptimizer';sec.className='advanced-section';sec.innerHTML='<div id="hdOptExp"></div>';anchor.insertAdjacentElement('afterend',sec);hdOptExpRender()}
function hdOptSortieRows(){return hdOptLoad('harbordesk-sortie-log-v1',[])}
function hdOptCostGroup(){const rows=hdOptSortieRows(),m={};for(const x of rows){const k=x.map||'未設定';(m[k]??=[]).push(x)}return m}
function hdOptCostStats(rows){const n=rows.length||1,sum=k=>rows.reduce((a,x)=>a+(Number(x[k])||0),0),rate=fn=>Math.round(rows.filter(fn).length/n*100);return {count:rows.length,fuel:sum('fuel')/n,ammo:sum('ammo')/n,steel:sum('steel')/n,bauxite:sum('bauxite')/n,buckets:sum('buckets')/n,boss:rate(x=>x.boss),s:rate(x=>x.result==='S'),retreat:rate(x=>x.retreat||x.result==='撤退')}}
function hdOptCostRender(){const host=document.getElementById('hdOptCost');if(!host)return;const groups=hdOptCostGroup(),maps=Object.keys(groups).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),selected=document.getElementById('hdOptCostMap')?.value||maps[0]||'',runs=Number(document.getElementById('hdOptCostRuns')?.value)||50,s=selected?hdOptCostStats(groups[selected]):null;host.innerHTML=`<div class="section-head"><div><div class="eyebrow">COST FORECAST</div><h2>出撃コスト予測</h2></div><span class="muted">自分の周回実績ベース</span></div>${maps.length?`<div class="hd-go-grid2"><label>海域<select id="hdOptCostMap">${maps.map(m=>`<option ${m===selected?'selected':''}>${hdOptEsc(m)}</option>`).join('')}</select></label><label>予測周回数<input id="hdOptCostRuns" type="number" min="1" value="${runs}"></label></div><div class="hd-opt-cost"><div><span>記録</span><strong>${s.count}周</strong></div><div><span>燃料</span><strong>${Math.round(s.fuel*runs)}</strong><small>${s.fuel.toFixed(1)}/周</small></div><div><span>弾薬</span><strong>${Math.round(s.ammo*runs)}</strong><small>${s.ammo.toFixed(1)}/周</small></div><div><span>鋼材</span><strong>${Math.round(s.steel*runs)}</strong><small>${s.steel.toFixed(1)}/周</small></div><div><span>ボーキ</span><strong>${Math.round(s.bauxite*runs)}</strong><small>${s.bauxite.toFixed(1)}/周</small></div><div><span>バケツ</span><strong>${Math.round(s.buckets*runs)}</strong><small>${s.buckets.toFixed(2)}/周</small></div></div><div class="hd-go-checks"><div class="ok">ボス到達 ${s.boss}% / S勝利 ${s.s}% / 撤退 ${s.retreat}%</div></div>`:'<div class="empty">出撃ログが貯まると予測できるよ。</div>'}`}
function hdOptCostEnsure(){if(document.getElementById('sortieCostForecast'))return;const anchor=document.getElementById('sortieLog');if(!anchor)return;const sec=document.createElement('section');sec.id='sortieCostForecast';sec.className='advanced-section';sec.innerHTML='<div id="hdOptCost"></div>';anchor.insertAdjacentElement('afterend',sec);hdOptCostRender()}
function hdOptFarmRender(){const host=document.getElementById('hdOptFarm');if(!host)return;const hunts=hdOptLoad('harbordesk-drop-hunts-v1',[]),logs=hdOptSortieRows();host.innerHTML=`<div class="section-head"><div><div class="eyebrow">FARMING ANALYTICS+</div><h2>掘り分析</h2></div><span class="muted">掘り目標×周回ログ</span></div><div class="hd-opt-farm-list">${hunts.map(h=>{const r=logs.filter(x=>x.huntId===h.id),st=hdOptCostStats(r),drops=r.filter(x=>x.drop).length;return `<article class="${h.obtained?'done':''}"><div><strong>${hdOptEsc(h.ship)}</strong><span>${hdOptEsc(h.map)} ${hdOptEsc(h.node)} ${h.obtained?'・入手済み':''}</span></div><div class="hd-opt-metrics"><span>周回 <b>${h.runs||r.length}</b></span><span>S <b>${h.s||r.filter(x=>x.result==='S').length}</b></span><span>A <b>${h.a||r.filter(x=>x.result==='A').length}</b></span><span>Drop記録 <b>${drops}</b></span><span>バケツ/周 <b>${r.length?st.buckets.toFixed(2):'-'}</b></span><span>燃料/周 <b>${r.length?st.fuel.toFixed(0):'-'}</b></span></div></article>`}).join('')||'<div class="empty">掘り目標を追加すると分析できるよ。</div>'}</div>`}
function hdOptFarmEnsure(){if(document.getElementById('farmingAnalytics'))return;const anchor=document.getElementById('dropHuntingDb')||document.getElementById('sortieCostForecast');if(!anchor)return;const sec=document.createElement('section');sec.id='farmingAnalytics';sec.className='advanced-section';sec.innerHTML='<div id="hdOptFarm"></div>';anchor.insertAdjacentElement('afterend',sec);hdOptFarmRender()}
function hdOptQuestScore(){if(typeof HD_QUESTS==='undefined'||typeof HD_QUEST_EXTRA==='undefined'||typeof hdQPEntry!=='function'||typeof hdQPGoals!=='function')return {done:0,remaining:0};let done=0,remaining=0;for(const q of [...HD_QUESTS,...HD_QUEST_EXTRA]){const m=String(q.reward||'').match(/戦果\+(\d+)/);if(!m)continue;const score=Number(m[1])||0,g=hdQPGoals(q),r=hdQPEntry(q),complete=g.length&&g.every((x,i)=>(Number(r.values?.[i])||0)>=Number(x[1]));if(complete)done+=score;else remaining+=score}return {done,remaining}}
function hdOptRankRender(){const host=document.getElementById('hdOptRank');if(!host)return;const cfg=hdOptLoad(HD_RANK_KEY,{manual:0,target:0}),eo=typeof hdEOLoad==='function'&&typeof hdEOSummary==='function'?hdEOSummary(hdEOLoad()):{score:0},eoTotal=typeof HD_EO_MAPS!=='undefined'?HD_EO_MAPS.reduce((a,x)=>a+(Number(x.score)||0),0):0,q=hdOptQuestScore(),total=(Number(cfg.manual)||0)+(Number(eo.score)||0)+q.done;host.innerHTML=`<div class="section-head"><div><div class="eyebrow">RANKING / SCORE</div><h2>EO・戦果管理</h2></div><span class="muted">HarborDesk上の確定/進捗</span></div><div class="hd-opt-cost"><div><span>EO獲得</span><strong>${eo.score||0}</strong><small>残り ${Math.max(0,eoTotal-(eo.score||0))}</small></div><div><span>定期任務進捗完了</span><strong>${q.done}</strong><small>未完了候補 ${q.remaining}</small></div><div><span>手動戦果</span><strong>${Number(cfg.manual)||0}</strong></div><div><span>合計</span><strong>${total}</strong></div></div><div class="hd-go-grid2"><label>その他/通常戦果を手動入力<input id="hdOptRankManual" type="number" value="${Number(cfg.manual)||0}"></label><label>自分の目標値<input id="hdOptRankTarget" type="number" value="${Number(cfg.target)||0}"></label></div><button type="button" class="primary" data-opt-rank-save>保存</button>${cfg.target?`<div class="hd-go-checks"><div class="${total>=cfg.target?'ok':'warn'}">目標まで ${Math.max(0,cfg.target-total)}</div></div>`:''}<div class="hd-go-note">ランキング順位や他提督の戦果は取得していないため、ここでは自分のEO・定期任務・手動入力の合計を管理する。</div>`}
function hdOptRankEnsure(){if(document.getElementById('rankingTracker'))return;const anchor=document.getElementById('eoTracker')||document.getElementById('questDatabase');if(!anchor)return;const sec=document.createElement('section');sec.id='rankingTracker';sec.className='advanced-section';sec.innerHTML='<div id="hdOptRank"></div>';anchor.insertAdjacentElement('afterend',sec);hdOptRankRender()}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-opt-imp-add]')){document.getElementById('hdOptImpDialog')?.showModal();return}const step=e.target.closest?.('[data-opt-imp-step]');if(step){const rows=hdOptLoad(HD_OPT_IMPROVE_KEY,[]),g=rows.find(x=>x.id===step.dataset.optImpStep);if(g)g.current=Math.min(Number(g.target)||10,(Number(g.current)||0)+1);hdOptSave(HD_OPT_IMPROVE_KEY,rows);hdOptImproveRender();return}const del=e.target.closest?.('[data-opt-imp-del]');if(del){hdOptSave(HD_OPT_IMPROVE_KEY,hdOptLoad(HD_OPT_IMPROVE_KEY,[]).filter(x=>x.id!==del.dataset.optImpDel));hdOptImproveRender();return}const preset=e.target.closest?.('[data-opt-exp-minutes]');if(preset){hdOptExpSetMinutes(preset.dataset.optExpMinutes);return}const set=e.target.closest?.('[data-opt-exp-set]');if(set){try{if(typeof hdEFSaveSlot==='function'){hdEFSaveSlot(Number(set.dataset.fleet),set.dataset.optExpSet);if(typeof hdWSShowElement==='function')hdWSShowElement('expeditionFleetManager',true);else if(typeof hdQNJump==='function')hdQNJump('expeditionFleetManager');else document.getElementById('expeditionFleetManager')?.scrollIntoView({behavior:'smooth',block:'start'})}}catch{}return}if(e.target.closest?.('[data-opt-rank-save]')){hdOptSave(HD_RANK_KEY,{manual:Number(document.getElementById('hdOptRankManual')?.value)||0,target:Number(document.getElementById('hdOptRankTarget')?.value)||0});hdOptRankRender();return}})
document.addEventListener('change',e=>{if(e.target?.id==='hdOptExpResource'){hdOptExpResource=e.target.value;hdOptExpUpdateRows()}if(e.target?.id==='hdOptExpHours'||e.target?.id==='hdOptExpMinutes'){const hours=document.getElementById('hdOptExpHours'),minutes=document.getElementById('hdOptExpMinutes'),raw=(Number(hours?.value)||0)*60+(Number(minutes?.value)||0);if(hours?.value===''||minutes?.value===''||raw<15||raw>1440||!Number.isInteger(raw))hdOptExpSetMinutes(raw)}if(e.target?.id==='hdOptCostMap')hdOptCostRender()})
document.addEventListener('input',e=>{if(e.target?.id==='hdOptExpHours'||e.target?.id==='hdOptExpMinutes'){const hours=document.getElementById('hdOptExpHours'),minutes=document.getElementById('hdOptExpMinutes');if(hours?.value!==''&&minutes?.value!==''){hdOptExpMinutes=hdOptExpClamp(Number(hours.value)*60+Number(minutes.value));hdOptExpUpdateRows()}}if(e.target?.id==='hdOptCostRuns')hdOptCostRender()})
window.addEventListener('load',()=>setTimeout(()=>{hdOptImproveEnsure();hdOptExpEnsure();hdOptCostEnsure();hdOptFarmEnsure();hdOptRankEnsure()},2000));setTimeout(()=>{hdOptImproveEnsure();hdOptExpEnsure();hdOptCostEnsure();hdOptFarmEnsure();hdOptRankEnsure()},2600);
